"# Sample code to generate the Mandelbrot set" 
"import matplotlib.pyplot as plt" 
"import numpy as np" 
"def mandelbrot(c, max_iter):" 
"    z = 0" 
"    n = 0" 
"    while abs(z) <= 2 and n < max_iter:" 
"        z = z*z + c" 
"        n += 1" 
"    return n" 
"def display(width, height, x_min, x_max, y_min, y_max, max_iter):" 
"    r1 = np.linspace(x_min, x_max, width)" 
"    r2 = np.linspace(y_min, y_max, height)" 
"    return (r1, r2, np.array([[mandelbrot(complex(r, i), max_iter) for r in r1] for i in r2]))" 
"r1, r2, mandelbrot_set = display(800, 800, -2, 1, -1.5, 1.5, 100)" 
"plt.imshow(mandelbrot_set, extent=(-2, 1, -1.5, 1.5), cmap='hot')" 
"plt.colorbar()" 
"plt.show()" 
